MISTRAL_API_KEY = "vf2jKowUgiX2Z1lxSjc2X7wrPoUnczkh"
OPENAI_API_KEY = "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"